config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
#  match 'inventory', :to => 'inventories#index'
#  match 'inventory/:id', :to => 'inventories#show', :via => "get"
#  match 'inventory/:action/:id', :to => 'inventories#show'
#  match 'inventory_types/new', :to => 'inventory_types#new'

  resources :inventories 
#  resources :inventories, :to => 'inventory'
  resources :inventory_types
  resources :inventory_brands
  resources :inventory_locates 
  resources :inventory_checkins 
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :inventory_type
  belongs_to :inventory_brand
  has_many :inventory_checkin
end

app/models/inventory_brand.rb
class InventoryBrand < ActiveRecord::Base
	has_many :inventories
end

app/models/inventory_checkin.rb
class InventoryCheckin < ActiveRecord::Base
  belongs_to :inventory 
  belongs_to :user
  belongs_to :locate
end

app/models/inventory_locate.rb
class InventoryLocate < ActiveRecord::Base
	has_many :invetory_checkins
end

app/models/inventory_type.rb
class InventoryType < ActiveRecord::Base
  has_many :inventories
  validates :name, :presence=>true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

  def show 
    @inventory = Inventory.find(params[:id], :joins => [:inventory_brand, :inventory_type])
  end

  def index
	@inventories = Inventory.find(:all, :order => "name asc", :joins=> [:inventory_type, :inventory_brand]);
	@total_consumption = Inventory.sum('consumption')
	@total_price = Inventory.sum('price')
  end

  def new
	@inventory = Inventory.new
	@inventory_type = InventoryType.find(:all, :order => "name asc");
	@inventory_brand = InventoryBrand.find(:all, :order => "name asc");
  end

  def create
	@inventory = Inventory.new(params[:inventory])
	if @inventory.save
        flash[:notice] = l(:label_inventory_created, :title => @inventory.name)
		redirect_to({:action => 'index'})
	else
		render(:action => 'new')
	end
  end

  def edit
    @inventory = Inventory.find(params[:id])
	@inventory_type = InventoryType.find(:all, :order => "name asc");
	@inventory_brand = InventoryBrand.find(:all, :order => "name asc");
  end

  def destroy
	Inventory.find(params[:id]).destroy
	flash[:notice] = l(:label_inventory_destroy)
	redirect_to({:action => 'index'})
  end

  def update
    @inventory = Inventory.find(params[:id])
    @inventory.update_attributes(params[:inventory])
    if @inventory.save
		flash[:notice] = l(:notice_successful_update)
		redirect_to({:action=>'index'})
	end
  end
end

app/controllers/inventory_brands_controller.rb
class InventoryBrandsController < ApplicationController

  def show 
    @inventory_brand = InventoryBrand.find(params[:id])
  end

  def index
	@inventory_brand = InventoryBrand.find(:all, :order => "name asc")
  end

  def new
	@inventory_brand = InventoryBrand.new
  end

  def create
	@inventory_brand = InventoryBrand.new(params[:inventory_brand])
	if @inventory_brand.valid?
 		if @inventory_brand.save
        	flash[:notice] = l(:label_inventory_brand_created, :title => @inventory_brand.name)
			redirect_to({:action => 'index'})
		else
			flash[:error] = l(:notice_error_new)
			render :new
		end
	else
		flash[:error] = l(:notice_error_new)
  		flash[:error] << "<ul>"
    	@inventory_type.errors.full_messages.each do |msg|
  		  flash[:error] << "<li>" + msg + "</li>"
        end
  		flash[:error] << "</ul>"
		render :new
	end
  end

  def edit
    @inventory_brand = InventoryBrand.find(params[:id])
  end

  def destroy
	InventoryBrand.find(params[:id]).destroy
	flash[:notice] = l(:label_inventory_brand_destroy)
	redirect_to({:action => 'index'})
  end

  def update
    @inventory_brand = InventoryBrand.find(params[:id])
    @inventory_brand.update_attributes(params[:inventory_brand])
	if @inventory_brand.valid?
    	if @inventory_brand.save
			flash[:notice] = l(:notice_successful_update)
		  	redirect_to({:action=>'index'})
		end
	else
		flash[:error] = l(:notice_error_new)
  		flash[:error] << "<ul>"
    	@inventory_type.errors.full_messages.each do |msg|
  		  flash[:error] << "<li>" + msg + "</li>"
        end
  		flash[:error] << "</ul>"
		render :edit
	end
  end
end

app/controllers/inventory_checkin_controller.rb
class InventoryCheckinController < ApplicationController
  unloadable


  def new
  end

  def index
  end

  def show
  end
end

app/controllers/inventory_checkins_controller.rb
class InventoryCheckinsController < ApplicationController

  def new
	@inventory_checkin = InventoryCheckin.new
	@inventory_locate = InventoryLocate.find(:all, :order => "name asc")
	@inventory = Inventory.find(params[:inventory_id])
    @user = User.find(:all, :order => "firstname asc, lastname asc")
    @inventory_checkin.user_id = session[:user_id] 
    @inventory_checkin.inventory_id = params[:inventory_id]
  end

  def create
	@inventory_checkin = InventoryCheckin.new(params[:inventory_checkin])
	@inventory_checkin.create_at = DateTime.current
	if @inventory_checkin.save
        flash[:notice] = l(:label_inventory_created)
		redirect_to({:action => 'index'})
	else
		render(:action => 'new')
	end
  end

  def index
  end

  def show
  end
end

app/controllers/inventory_locates_controller.rb
class InventoryLocatesController < ApplicationController
  unloadable


  def new
	@inventory_locate = InventoryLocate.new
  end

  def edit
	@inventory_locate = InventoryLocate.find(params[:id]);
  end

  def index
	@inventory_locate = InventoryLocate.find(:all);
  end

  def create
	@inventory_locate = InventoryLocate.new(params[:inventory_locate])
	if @inventory_locate.save
        flash[:notice] = l(:label_inventory_locate_created, :title => @inventory_locate.name)
		redirect_to({:action => 'index'})
	else
		render(:action => 'new')
    end
  end

  def update
    @inventory_locate = InventoryiLocate.find(params[:id])
    @inventory_locate.update_attributes(params[:inventory_ilocate])
    if @inventory_locate.save
		flash[:notice] = l(:notice_successful_update)
		redirect_to({:action=>'index'})
	end
  end

  def show
	@inventory_locate = InventoryLocate.find(params[:id]);
  end

  def destroy
    InventoryLocate.find(params[:id]).destroy
    flash[:notice] = l(:label_inventory_locate_destroy)
    redirect_to({:action=>'index'})
  end
end

app/controllers/inventory_types_controller.rb
class InventoryTypesController < ApplicationController
  unloadable

  def show 
    @inventory_type = InventoryType.find(params[:id])
  end

  def index
	@inventory_type = InventoryType.find(:all, :order => "name asc")
  end

  def new
	@inventory_type = InventoryType.new
  end

  def create
	@inventory_type = InventoryType.new(params[:inventory_type])
	if @inventory_type.valid?
	  if @inventory_type.save
          flash[:notice] = l(:label_inventory_type_created, :title => @inventory_type.name)
		  redirect_to({:action => 'show', :id =>@inventory_type.id})
	  end
    else 
		flash[:error] = l(:notice_error_new)
  		flash[:error] << "<ul>"
    	@inventory_type.errors.full_messages.each do |msg|
  		  flash[:error] << "<li>" + msg + "</li>"
        end
  		flash[:error] << "</ul>"
		render :new
	end
  end

  def edit
    @inventory_type = InventoryType.find(params[:id])
  end

  def destroy
	InventoryType.find(params[:id]).destroy
	flash[:notice] = l(:label_inventory_type_destroy)
	redirect_to({:action => 'index'})
  end

  def update
    @inventory_type = InventoryType.find(params[:id])
    @inventory_type.update_attributes(params[:inventory_type])
	if @inventory_type.valid?
    	if @inventory_type.save
			flash[:notice] = l(:notice_successful_update)
			redirect_to({:action=>'index'})
		end
	else
		flash[:error] = l(:notice_error_update)
  		flash[:error] << "<ul>"
    	@inventory_type.errors.full_messages.each do |msg|
  		  flash[:error] << "<li>" + msg + "</li>"
        end
  		flash[:error] << "</ul>"
		render :edit
	end
  end
end

app/helpers/inventory_brands_helper.rb
module InventoryBrandsHelper
end

app/helpers/inventory_checkin_helper.rb
module InventoryCheckinHelper
end

app/helpers/inventory_checkins_helper.rb
module InventoryCheckinsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/inventory_locates_helper.rb
module InventoryLocatesHelper
end

app/helpers/inventory_types_helper.rb
module InventoryTypesHelper
end

app/views/inventories/_form.html.erb
<div class="box tabular">
	<p><%= f.text_field :name, :required =>true, :size=>60 %></p>
	<p><%= f.select :inventory_type_id, @inventory_type.map{|c| [c.name, c.id]}, :include_blank => true, :required=>true %></p>
	<p><%= f.select :inventory_brand_id, @inventory_brand.map{|c| [c.name, c.id]}, :include_blank => true, :required=>true %></p>
	<p><%= f.text_field :serial, :required =>true, :size=>60 %></p>
	<p><%= f.text_field :macaddress, :size=>60 %></p>
	<p><%= f.text_field :inventoryid, :required =>true, :size=>60 %></p>
	<p><%= f.text_field :model, :size=>60 %></p>
	<p><%= f.text_field :price, :size=>60 %></p>
	<p><%= f.text_field :consumption, :size=>60 %></p>
	<p><%= f.text_area :comment, :required =>true, :rows=>5, :cols=>60 %></p>
	<p><%= f.check_box :outofservice, :size=>60 %></p>
</div>

app/views/inventories/create.html.erb
<h2>InventoryController#create</h2>

app/views/inventories/destroy.html.erb
<h2>InventoryController#destroy</h2>

app/views/inventories/edit.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list),    inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),   inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_edit) %></h1>
<%= labelled_form_for(@inventory) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/inventories/index.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new), new_inventory_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),   inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>
<h2>Inventory List</h2>

<% if @inventories.empty? %>
	<p class="nodata">No data to display</p>
<% else %>
<table class="list" width="60%">
<thead>
	<tr>
		<th>Id</th>
		<th><%=t :field_name %></th>
		<th><%=t :field_type %></th>
		<th><%=t :field_serial %></th>
		<th><%=t :field_inventory %></th>
		<th><%=t :field_brand %></th>
		<th><%=t :field_model %></th>
		<th><%=t :field_user %></th>
		<th><%=t :field_locate %></th>
		<th><%=t :field_consumption %></th>
		<th><%=t :field_price %></th>
		<th>&nbsp;</th>
	</tr>
</thead>
	<% @inventories.each do |i| %>
		<tr>
		<td align="center"><%= link_to i.id, inventory_path(i)%></th>
		<td><%= link_to i.name, inventory_path(i) %></td>
		<td><%=t i.serial %></td>
		<td><%=t i.inventory_type.name%></td>
		<td><%=t i.inventoryid %></td>
		<td><%= link_to i.inventory_brand.name, inventory_brand_path(i.inventory_brand)  %></td>
		<td><%=t i.model %></td>
		<td></td>
		<td></td>
		<td align="right"><%= i.consumption %></td>
		<td align="right"><%= number_to_currency(i.price) %></td>
		<td>
			<%= link_to "", edit_inventory_path(i), :class => "icon icon-edit" %>
			<%= link_to "", inventory_path(i), :confirm=> "Are you sure?", :class => "icon icon-del", :method => :delete %>
			<%= link_to "", new_inventory_checkin_path(:inventory_id=>i), :class => "icon icon-package" %>
		</td>
		</tr>
	<% end %>
	<tfoot>
		<tr>
		<th align="right" colspan="9">Total</th>
		<th align="right"><%= @total_consumption =%></th>
		<th align="right"><%= number_to_currency(@total_price) =%></th>
		<th>&nbsp</th>
		</tr>
	</tfoot>
</table>
<% end %>

app/views/inventories/loclist.html.erb
<h2>InventoryController#loclist</h2>

app/views/inventories/new.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_new) %></h1>

<%= labelled_form_for(@inventory) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/inventories/print.html.erb
<h2>InventoryController#print</h2>

app/views/inventories/show.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:edit),    edit_inventory_path(@inventory), :class => "icon icon-edit" %>
	<%= link_to t(:inventory_list),    inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),   inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_show) %>: <%= @inventory.name %></h1>
<table>
<tr><th align="right"><%=l(:field_serial)%>:</th><td> <%= @inventory.serial %></td></tr>
<tr><th align="right"><%=l(:field_inventoryid)%>:</th><td><%= @inventory.inventoryid %></td></tr>
<tr><th align="right"><%=l(:field_inventory_type)%>:</th><td><%= @inventory.inventory_type.name %></td></tr>
<tr><th align="right"><%=l(:field_inventory_brand)%> / <%=l(:field_model)%></th><td><%= @inventory.inventory_brand.name %> / <%=@inventory.model%></td></tr>
<tr><th align="right"><%=l(:field_price)%>:</th><td>$<%= @inventory.price %></td></tr>
<tr><th align="right"><%=l(:field_consumption)%>:</th><td><%= @inventory.consumption %> watts</td></tr>
</table>
<% if @inventory.inventory_checkins.empty? %>
	<p class="nodata">No checkin to display</p>
<% else %>
<h2><%= l(:h2_inventory_show_checkin)%></h2>
<table>
<% @inventory.inventory_checkins.each do |c| %>
	<tr>
	<td><%= link_to c.user.firstname, user_path(c.user) %></td>
	<td><%= c.create_at %></td>
	<td><%= c.comment %></td>
	</tr>
<% end %>
</table>
<% end %>

app/views/inventories/update.html.erb
<h2>InventoryController#update</h2>

app/views/inventory_brands/_form.html.erb
<div class="box tabular">
	<p><%= f.text_field :name, :required =>true, :size=>60 %></p>
</div>

app/views/inventory_brands/create.html.erb
<h2>InventoryLocatesController#create</h2>

app/views/inventory_brands/edit.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list), inventory_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_brand_edit) %></h1>

<%= labelled_form_for(@inventory_brand) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/inventory_brands/index.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_brand),  new_inventory_brand_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type), inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>
<h1><%= l(:h1_inventory_brand) %></h1>

<% if @inventory_brand.empty? %>
	<p class="nodata">No data to display</p>
<% else %>
<table class="list" width="25%">
<thead>
	<tr>
		<th>Id</th>
		<th><%=t :field_name %></th>
		<th>&nbsp;</th>
	</tr>
</thead>
<tbody>
	<% @inventory_brand.each do |e| %>
		<tr>
			<td align="center" width="20px"><%= e.id %></td>
			<td><%= e.name%></td>
			<td>
				<%= link_to "", edit_inventory_brand_path(e), :class => "icon icon-edit" %>
				<%= link_to "", inventory_brand_path(e), :confirm=> "Are you sure?", :class => "icon icon-del", :method => :delete %>
			</td>
		</tr>
	<% end %>	
</tbody>
</table>
<% end %>

app/views/inventory_brands/new.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_brand_new) %></h1>

<%= labelled_form_for(@inventory_brand) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/inventory_brands/show.html.erb
<h1><%= l(:h1_inventory_brand_show) %></h1>

app/views/inventory_brands/update.html.erb
<h2>InventoryLocatesController#update</h2>

app/views/inventory_checkins/index.html.erb
<h2>InventoryCheckinsController#index</h2>

app/views/inventory_checkins/new.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
</div>


<h1><%= l(:h1_inventory_checkin)%>: <%= @inventory.name %></h1>
<%= labelled_form_for(@inventory_checkin) do |f| %>
<div class="box tabular">
	<p><%= f.select :inventory_locate_id, @inventory_locate.map{|c| [c.name, c.id]}, :include_blank => true, :required=>true %></p>
	<p><%= f.select :user_id, @user.map{|c| [c.name, c.id]}, :include_blank => true, :required=>true %></p>
	<p><%= f.text_area :comment %></p>
	<%= f.hidden_field :inventory_id%>
</div>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/inventory_checkins/show.html.erb
<h2>InventoryCheckinsController#show</h2>

app/views/inventory_locates/_form.html.erb
<div class="box tabular">
	<p><%= f.text_field :name, :required =>true, :size=>60 %></p>
	<p><%= f.text_area :address, :rows=>5, :required => true, :size=>60 %></p>
	<p><%= f.text_field :city, :size=>60 %></p>
</div>

app/views/inventory_locates/create.html.erb
<h2>InventoryLocatesController#create</h2>

app/views/inventory_locates/edit.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_locate_edit) %></h1>

<%= labelled_form_for(@inventory_locate) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/inventory_locates/index.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_locate),  new_inventory_locate_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), "inventory", :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_types),  "inventory_types", :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  "inventory_brands", :class => "icon icon-report" %>
</div>
<h1><%= l(:h1_inventory_locate) %></h1>

<% if @inventory_locate.empty? %>
	<p class="nodata">No data to display</p>
<% else %>
<table class="list" width="25%">
<thead>
	<tr>
		<th>Id</th>
		<th><%=t :field_name %></th>
		<th><%=t :field_city %></th>
		<th>&nbsp;</th>
	</tr>
</thead>
<tbody>
	<% @inventory_locate.each do |e| %>
		<tr>
			<td align="center" width="20px"><%= e.id %></td>
			<td><%= e.name%></td>
			<td><%= e.city%></td>
			<td>
				<%= link_to "", edit_inventory_locate_path(e), :class => "icon icon-edit" %>
				<%= link_to "", inventory_locate_path(e), :confirm=> "Are you sure?", :class => "icon icon-del", :method => :delete %>
			</td>
		</tr>
	<% end %>	
</tbody>
</table>
<% end %>

app/views/inventory_locates/new.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_list_locate),  inventory_locates_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_type),  inventory_types_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_locate_new) %></h1>

<%= labelled_form_for(@inventory_locate) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/inventory_locates/show.html.erb
<h2>InventoryLocatesController#show</h2>

app/views/inventory_locates/update.html.erb
<h2>InventoryLocatesController#update</h2>

app/views/inventory_types/_form.html.erb
<%= form_for(@inventory_type) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
<% end %>

app/views/inventory_types/create.html.erb
<h2>InventoryTypeController#create</h2>

app/views/inventory_types/destroy.html.erb
<h2>InventoryTypeController#destroy</h2>

app/views/inventory_types/edit.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_type),  new_inventory_type_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:h1_inventory_type_edit) %></h1>

<%= form_for(@inventory_type) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= submit_tag l(:button_save) %>
<% end %>

app/views/inventory_types/index.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_type),  new_inventory_type_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_list_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>
<h1><%= l(:h1_inventory_type) %></h1>

<% if @inventory_type.empty? %>
	<p class="nodata">No data to display</p>
<% else %>
<table class="list" width="25%">
<thead>
	<tr>
		<th>Id</th>
		<th><%=t :field_name %></th>
		<th>&nbsp;</th>
	</tr>
</thead>
<tbody>
	<% @inventory_type.each do |e| %>
		<tr>
			<td align="center" width="20px"><%= e.id %></td>
			<td><%= e.name%></td>
			<td>
				<%= link_to "", edit_inventory_type_path(e), :class => "icon icon-edit" %>
				<%= link_to "", inventory_type_path(e), :confirm=> "Are you sure?", :class => "icon icon-del", :method => :delete %>
			</td>
		</tr>
	<% end %>	
</tbody>
</table>
<% end %>

app/views/inventory_types/new.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_type),  new_inventory_type_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), inventories_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_new_brand),  inventory_brands_path, :class => "icon icon-report" %>
	<%= link_to t(:inventory_new_locate), inventory_locates_path, :class => "icon icon-report" %>
</div>

<h1><%= l(:new_inventory_type) %></h1>
<div class="box tabular">


<%= labelled_form_for(@inventory_type) do |f| %>
    <p><%= f.text_field :name, :required => true, :size => 60 %></p>
	<%= submit_tag l(:button_create) %>
<% end %>
</div>

app/views/inventory_types/show.html.erb
<% html_title t(:inventory_label) %>
<div class="contextual">
	<%= link_to t(:inventory_new_type),  new_inventory_type_path, :class => "icon icon-add" %>
	<%= link_to t(:inventory_list), "inventory", :class => "icon icon-report" %>
	<%= link_to t(:inventory_new_brand),  "inventory_brand", :class => "icon icon-report" %>
	<%= link_to t(:inventory_new_locate), "inventory_locate", :class => "icon icon-report" %>
</div>
<h1><%= l(:h1_inventory_type_show) %></h1>
<h2><%= @inventory_type.name %></h2>

app/views/inventory_types/update.html.erb
<h2>InventoryTypeController#update</h2>